// vue-app/src/components/Nav.vue
<template>
  <nav>
    <ul>
      <li>
        <router-link to="/vue">Home</router-link>
      </li>
      <li>
        <router-link to="/vue/about">About</router-link>
      </li>
    </ul>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Nav",
});
</script>

// react-app/src/components/Nav.tsx

import React from 'react'
import { Link } from 'react-router-dom'
import RoutesList from '../routes'

const Nav = () => {
  return (
    <nav>
      <ul>
        {RoutesList.map((route) => (
          <li key={route.path}>
            <Link to={route.path}>{route.name}</Link>
          </li>
        ))}
      </ul>
    </nav>
  )
}

export default Nav
