// container-react/src/components/wrapper/AngularWrapper.tsx
import React, { Suspense, useEffect, useRef, useState } from "react";

// const AngularApp = React.lazy(() => import("angularApp/Module"));
import AngularApp from "angularApp/Module";
const AngularWrapperLoader = () => {
  //   console.log("AngularWrapperLoader>> ", AngularApp);

  return (
    <Suspense fallback={<div>Loading...</div>}>
      <AngularWrapper />
    </Suspense>
  );
};

const AngularWrapper = () => {
  console.log("AngularWrapperLoader");
  const angularRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const loadAngularApp = async () => {
      if (angularRef.current) {
        angularRef.current.innerHTML = "<app-root></app-root>";
        try {
          const angularApp = await import("angularApp/Module").then((m) => {
            return m.default || m;
          });
        //   const AngularAppComponent = React.createElement(angularApp);
          angularApp.bootstrap(angularRef.current);
        } catch (error) {
          console.error("Angular on Mount [error]:", error);
        }
      }
    };
    loadAngularApp();
    return () => {
      if (angularRef.current) {
        angularRef.current.innerHTML = "";
      }
    };
  }, []);

  return (
    <>
      <h1>angular wrapper</h1>
      <div ref={angularRef}></div>
    </>
  );
};

export default AngularWrapperLoader;

// container/src/components/AngularWrapper.vue
<template>
  <div ref="angularRoot"></div>
</template>

<script lang="ts">
import { defineComponent, onMounted, onUnmounted, ref } from "vue";
import { PropType } from "vue";

export default defineComponent({
  name: "AngularWrapper",
  props: {
    component: {
      type: [Function, Object] as PropType<() => Promise<any>>,
      required: true,
    },
  },
  setup(props) {
    const angularRoot = ref<HTMLElement | null>(null);
    let moduleRef: any = null;

    onMounted(async () => {
      if (angularRoot.value && typeof props.component === "function") {
        const el = angularRoot.value;
        el.innerHTML = "<app-root></app-root>";

        try {
          const module = await props.component();
          console.log("Angular on Mount [info]:", "Yüklenen modül:", module);

          if (module?.bootstrap) {
            moduleRef = await module.bootstrap(el);
          } else {
            console.error("Angular on Mount [error]:");
          }
        } catch (error) {
          console.error("Angular on Mount [error]:", error);
        }
      }
    });

    onUnmounted(() => {
      if (moduleRef) {
        moduleRef.destroy();
      }
      if (angularRoot.value) {
        angularRoot.value.innerHTML = "";
      }
    });

    return {
      angularRoot,
    };
  },
});
</script>
