// vue-app/src/components/Nav.vue
<template>
  <nav>
    <ul>
      <li>
        <router-link to="/vue">Home</router-link>
      </li>
      <li>
        <router-link to="/vue/about">About</router-link>
      </li>
    </ul>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Nav",
});
</script>

// container-react/src/components/nav/Nav.tsx
import React from "react";

import RoutesList from "../../router/routes";
import { Link } from "react-router-dom";
const Nav = () => {
  return (
    <div>
      <ul>
        {RoutesList.map((route) => (
          <li key={route.path}>
            <a href={route.path}>{route.name}</a>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Nav;
